version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
